// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtnMc4cky_lZfqztPs8EOMn_kF7lcpC94',
    appId: '1:676703684103:web:f4c721e7be587f7644cca2',
    messagingSenderId: '676703684103',
    projectId: 'my-preppal',
    authDomain: 'my-preppal.firebaseapp.com',
    storageBucket: 'my-preppal.appspot.com',
    measurementId: 'G-S1F792TMGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBibgVmQnuPgunzF0ICnRJiH3qX_dCtww4',
    appId: '1:676703684103:android:8d5a580a7a6cf4ca44cca2',
    messagingSenderId: '676703684103',
    projectId: 'my-preppal',
    storageBucket: 'my-preppal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArHe1AN_enwuWPks12CNZ99RXyu9kTQwQ',
    appId: '1:676703684103:ios:1e49e8e2cc90455344cca2',
    messagingSenderId: '676703684103',
    projectId: 'my-preppal',
    storageBucket: 'my-preppal.appspot.com',
    iosBundleId: 'com.example.prepPal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArHe1AN_enwuWPks12CNZ99RXyu9kTQwQ',
    appId: '1:676703684103:ios:1e49e8e2cc90455344cca2',
    messagingSenderId: '676703684103',
    projectId: 'my-preppal',
    storageBucket: 'my-preppal.appspot.com',
    iosBundleId: 'com.example.prepPal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtnMc4cky_lZfqztPs8EOMn_kF7lcpC94',
    appId: '1:676703684103:web:0a11794fdf2899b244cca2',
    messagingSenderId: '676703684103',
    projectId: 'my-preppal',
    authDomain: 'my-preppal.firebaseapp.com',
    storageBucket: 'my-preppal.appspot.com',
    measurementId: 'G-Y241XGQC5Y',
  );
}
